<?php
/**
 * Class that operate on table '${table_name}'.
 * @author: Nelson Ariza
 * @date: ${date}
 */
class ${plural_class_name}DAO extends DAO{
    
    /**
 	* Update record in table ${table_name}
 	*/
	public function actualizar($${var_name}) {
        $cantidadActualizada=0;
		$sql = 'UPDATE ${table_name} SET ${update_fields} WHERE ${pk} = ?';${prepare_parameters}${prepare_where}
        $stmt = $this->conn->prepare($sql);${parameter_setter}${where_setter}
        $stmt->execute();
		$cantidadActualizada=$stmt->rowCount();
        return $cantidadActualizada;
	}
    
    /**
    * Get records from table ${table_name} by pk (${pk})
    */
    public function buscarFila($${pk}) {
        $sql = 'SELECT * FROM ${table_name} WHERE ${pk}=?';
        $var1=$${pk};
        $stmt = $this->conn->prepare($sql);
        $stmt->bindparam(1, $var1);
        $stmt->execute();
        if ($this->existePorId($${pk})) {
            return $stmt->fetchAll()[0];
        } else {
            return null;
        }
    }

    /**
    * Get onjects from table ${table_name} by pk (${pk})
    */
    public function buscarObjeto($${pk}) {
        $sql = 'SELECT * FROM ${table_name} WHERE ${pk}=?';
        $var1=$${pk};
        $stmt = $this->conn->prepare($sql);
        $stmt->bindparam(1, $var1);
        $stmt->execute();
        if ($this->existePorId($${pk})) {
            $fila=$stmt->fetchAll()[0];${crear_variables}
            ${crear_objeto}${asignar_atributos}
            return $${dto_name};
            
        } else {
            return null;
        }
    }
    
    /**
	* Count all records in table ${table_name}
	*/
    public function contar() {
        $sql = 'SELECT * FROM ${table_name}';
        return count($this->conn->query($sql)->fetchAll());
	}
    
    /**
    * Delete record from table ${table_name} by pk (${pk})
    */
    public function eliminar($${pk}) {
        $sql = 'DELETE FROM ${table_name} WHERE ${pk}=?';
        $var1=$${pk};
        $stmt = $this->conn->prepare($sql);
        $stmt->bindparam(1, $var1);
        $stmt->execute();
        $cantidadEliminada=$stmt->rowCount();
        return $cantidadEliminada;
    }

    /**
    * Check if exists a record in table ${table_name} by pk (${pk})
    */
     public function existe($${var_name}) {
        $sql = 'SELECT * FROM ${table_name} WHERE ${pk}=?';
        $var1=$${var_name}->get${pk2}();
        $stmt = $this->conn->prepare($sql);
        $stmt->bindparam(1, $var1);
        $stmt->execute();
        $conteo=count($stmt->fetchAll());
        if ($conteo==0){
            return false;
        } else {
            return true;
        }
    }
    
    /**
    * Check if exists a record in table ${table_name} by pk (${pk})
    */
     public function existePorId($${pk}) {
        $sql = 'SELECT * FROM ${table_name} WHERE ${pk}=?';
        $var1=$${pk};
        $stmt = $this->conn->prepare($sql);
        $stmt->bindparam(1, $var1);
        $stmt->execute();
        $conteo=count($stmt->fetchAll());
        if ($conteo==0){
            return false;
        } else {
            return true;
        }
    }
    
    /**
    * Insert a record in table ${table_name}
    */
    public function insertar(&$${var_name}) {
        $cantidadInsertada=0;
        try { 
            $this->conn->beginTransaction(); 
            $sql = 'INSERT INTO ${table_name} (${insert_fields}) VALUES(${question_marks})';${prepare_parameters_with_pks}
            $stmt = $this->conn->prepare($sql);${parameter_setter_with_pks}
            $stmt->execute();
            $cantidadInsertada=$stmt->rowCount();${autogenerated_id}
            $this->conn->commit();     
        } catch(PDOExecption $e) { 
            $this->conn->rollback(); 
            print "Error!: " . $e->getMessage() . "</br>"; 
        }   
        return $cantidadInsertada;
    }
    
    /**
	* Get all records from table ${table_name}
	*/
    public function listarFilas() {
        $sql = 'SELECT * FROM ${table_name} ORDER BY ${pk}';
        return $this->conn->query($sql);
    }

    /**
	* Get all objects from table ${table_name}
	*/
    public function listarObjetos() {
        $sql = 'SELECT * FROM ${table_name} ORDER BY ${pk}';
        $filas = $this->conn->query($sql);
        $lista= array();
        foreach ($filas as $fila) {${crear_variables}
            ${crear_objeto}${asignar_atributos}
            $lista[] = $${dto_name};
        }
        return $lista;
    }
	
}