<?php
/**
 * Class that operate on table '${table_name}'.
 * (Depurado), indentado correctamente
 * @author: Nelson Ariza
 * @date: ${date}
 */
class ${plural_class_name}DAO {

    protected $conn;

    function __construct() {
        $this->conn = ConnectionFactoryMySqlPDO::getConnection();
    }

	/**
 	* Update record in table ${table_name}
 	*/
	public function actualizar($${var_name}) {
        $cantidadActualizada=0;
		$sql = 'UPDATE ${table_name} SET ${update_fields} WHERE ${pk_where}';${prepare_parameters}${prepare_where}
        $stmt = $this->conn->prepare($sql);${parameter_setter}${where_setter}
        $cantidadActualizada=$stmt->execute();
        return $cantidadActualizada;
	}

    /**
    * Get records from table ${table_name} by pk (${pks})
    */
	public function buscar(${pks}) {
		$sql = 'SELECT * FROM ${table_name} WHERE ${pk_where}';${prepare_where2}
		$stmt = $this->conn->prepare($sql);${where_setter}
        $stmt->execute();
        if ($this->existe($id)) {
            $fila=$stmt->fetchAll()[0];
            return $fila;
        } else {
            return null;
        }
	}

    /**
	* Count all records in table ${table_name}
	*/
    public function contar() {
        $sql = 'SELECT * FROM ${table_name}';
        return count($this->conn->query($sql)->fetchAll());
	}

    /**
    * Delete record from table ${table_name} by pk (${pks})
    */
	public function eliminar(${pks}) {
		$sql = 'DELETE FROM ${table_name} WHERE ${pk_where}';${prepare_where2}
		$stmt = $this->conn->prepare($sql);${where_setter}
        $cantidadEliminada=$stmt->execute();
        return $cantidadEliminada;
	}


    /**
    * Check if exists a record in table ${table_name} by pk (${pks})
    */
     public function existe(${pks}) {
        $sql = 'SELECT * FROM ${table_name} WHERE ${pk_where}';${prepare_where2}
		$stmt = $this->conn->prepare($sql);${where_setter}
        $stmt->execute();
        $conteo=count($stmt->fetchAll());
        if ($conteo==0){
            return false;
        } else {
            return true;
        }
    }
	
    /**
    * Insert a record in table ${table_name}
    */
	public function insertar($${var_name}) {
        $cantidadInsertada=0;
        try { 
            $this->conn->beginTransaction(); 
            $sql = 'INSERT INTO ${table_name} (${insert_fields2}) VALUES (${question_marks2})';${prepare_where_insert}
            $stmt = $this->conn->prepare($sql);${where_setter_insert}
            $cantidadInsertada=$stmt->execute();${autogenerated_id}
            $this->conn->commit();     
        } catch(PDOExecption $e) { 
            $this->conn->rollback(); 
            print "Error!: " . $e->getMessage() . "</br>"; 
        }   
        return $cantidadInsertada;
	}

    /**
	* Get all records from table ${table_name}
	*/
    public function listar() {
        $sql = 'SELECT * FROM ${table_name}';
        return $this->conn->query($sql);
    }
	
}
