<?php
/**
 * Class that operate on table '${table_name}'.
 * @author: Nelson Ariza
 * @date: ${date}
 */
class ${plural_class_name}DAO {

    protected $conn;

    function __construct() {
        $this->conn = ConnectionFactoryMySqlPDO::getConnection();
    }

	/**
 	* Update record in table ${table_name}
 	*/
	public function actualizar($${var_name}) {
        $cantidadActualizada=0;
		$sql = 'UPDATE ${table_name} SET ${update_fields} WHERE ${pk_where}';${prepare_parameters}${prepare_where}
        $stmt = $this->conn->prepare($sql);${parameter_setter}${where_setter}
        $stmt->execute();
        $cantidadActualizada=$stmt->rowCount();
        return $cantidadActualizada;
	}

    /**
    * Get records from table ${table_name} by pk (${pks})
    */
	public function buscarFila(${pks}) {
		$sql = 'SELECT * FROM ${table_name} WHERE ${pk_where}';${prepare_where2}
		$stmt = $this->conn->prepare($sql);${where_setter2}
        $stmt->execute();
        if ($this->existePorId(${pks})) {
            $fila=$stmt->fetchAll()[0];
            return $fila;
        } else {
            return null;
        }
	}

    /**
    * Get objects from table ${table_name} by pk (${pks})
    */
	public function buscarObjeto(${pks}) {
		$sql = 'SELECT * FROM ${table_name} WHERE ${pk_where}';${prepare_where2}
		$stmt = $this->conn->prepare($sql);${where_setter2}
        $stmt->execute();
        if ($this->existePorId(${pks})) {
             $fila=$stmt->fetchAll()[0];${crear_variables}
            ${crear_objeto}${asignar_atributos}
            return $${dto_name};
        } else {
            return null;
        }
	}

    /**
	* Count all records in table ${table_name}
	*/
    public function contar() {
        $sql = 'SELECT * FROM ${table_name}';
        return count($this->conn->query($sql)->fetchAll());
	}

    /**
    * Delete record from table ${table_name} by pk (${pks})
    */
	public function eliminar(${pks}) {
		$sql = 'DELETE FROM ${table_name} WHERE ${pk_where}';${prepare_where2}
		$stmt = $this->conn->prepare($sql);${where_setter2}
        $stmt->execute();
        $cantidadEliminada=$stmt->rowCount();
        return $cantidadEliminada;
	}

    /**
    * Check if exists a record in table ${table_name} by pk (${pks})
    */
     public function existe($${var_name}) {
        $sql = 'SELECT * FROM ${table_name} WHERE ${pk_where}';${prepare_where3}
		$stmt = $this->conn->prepare($sql);${where_setter2}
        $stmt->execute();
        $conteo=count($stmt->fetchAll());
        if ($conteo==0){
            return false;
        } else {
            return true;
        }
    }

    /**
    * Check if exists a record in table ${table_name} by pk (${pks})
    */
     public function existePorId(${pks}) {
        $sql = 'SELECT * FROM ${table_name} WHERE ${pk_where}';${prepare_where2}
		$stmt = $this->conn->prepare($sql);${where_setter2}
        $stmt->execute();
        $conteo=count($stmt->fetchAll());
        if ($conteo==0){
            return false;
        } else {
            return true;
        }
    }
	
    /**
    * Insert a record in table ${table_name}
    */
	public function insertar($${var_name}) {
        $cantidadInsertada=0;
        try { 
            $this->conn->beginTransaction(); 
            $sql = 'INSERT INTO ${table_name} (${insert_fields}) VALUES (${question_marks})';${prepare_where_insert}
            $stmt = $this->conn->prepare($sql);${where_setter_insert}
            $stmt->execute();
            $cantidadInsertada=$stmt->rowCount();${autogenerated_id}
            $this->conn->commit();     
        } catch(PDOExecption $e) { 
            $this->conn->rollback(); 
            print "Error!: " . $e->getMessage() . "</br>"; 
        }   
        return $cantidadInsertada;
	}

    /**
	* Get all records from table ${table_name}
	*/
    public function listarFilas() {
        $sql = 'SELECT * FROM ${table_name}';
        return $this->conn->query($sql);
    }
    
    /**
	* Get all objects from table ${table_name}
	*/
    public function listarObjetos() {
        $sql = 'SELECT * FROM ${table_name}';
        $filas = $this->conn->query($sql);
        $lista= array();
        foreach ($filas as $fila) {${crear_variables}
            ${crear_objeto}${asignar_atributos}
            $lista[] = $${dto_name};
        }
        return $lista;
    }
	
}
